version: '3'
services:
  tcc_rabbitmq:
    image: rabbitmq:3-management
    container_name: tcc_rabbitmq
    restart: always
    build: .
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log [{console,[{level,debug}]}]
    ports:
      - 15672:15672
      - 5672:5672
      - 5682:5682
      - 5692:5692
    # volumes: 
    #   - ./dados:/var/lib/rabbitmq/

################################################ Mosquitto

#  mqtt:
#    container_name: tccprojectmosquitto
#    image: eclipse-mosquitto
#    restart: always
#    volumes: 
#      - ./dados/mosquitto/config:/mosquitto/config
#      - ./dados/mosquitto/data:/mosquitto/data
#      - ./dados/mosquitto/log:/mosquitto/log
#    ports:
#      - 1883:1883
#      - 9001:9001